[run]
skip-dirs = [".tmp"]
skip-dirs-use-default = "false"
modules-download-mode = "readonly"
go = "1.22"

[linters]
disable-all = true
enable = [
  "asasalint",
  "asciicheck",
  "bidichk",
  "bodyclose",
  "containedctx",
  "contextcheck",
  "durationcheck",
  "errcheck",
  "errchkjson",
  "errname",
  "errorlint",
  "exhaustive",
  "exportloopref",
  "forbidigo",
  "forcetypeassert",
  "gci",
  "gocheckcompilerdirectives",
  "gochecknoglobals",
  "gochecknoinits",
  "gocognit",
  "goconst",
  "gocritic",
  "gocyclo",
  "godot",
  "goerr113",
  "gofumpt",
  "gosec",
  "gosimple",
  "govet",
  "ineffassign",
  "interfacebloat",
  "makezero",
  "maintidx",
  "misspell",
  "nestif",
  "nilerr",
  "nilnil",
  "noctx",
  "nolintlint",
  "nosprintfhostport",
  "paralleltest",
  "perfsprint",
  "prealloc",
  "predeclared",
  "reassign",
  "revive",
  "sloglint",
  "staticcheck",
  "stylecheck",
  "tenv",
  "testpackage",
  "testableexamples",
  "thelper",
  "tparallel",
  "typecheck",
  "unconvert",
  "usestdlibvars",
  "unparam",
  "unused",
  "wastedassign",
  "wrapcheck",
  "wsl"
]

[linters-settings]

  [linters-settings.errcheck]
    check-type-assertions = true
    check-blank = true
    exclude-functions = [
      "encoding/json.Marshal",
      "encoding/json.MarshalIndent"
    ]

  [linters-settings.errchkjson]
    check-error-free-encoding = true

  [linters-settings.gocritic]
    enabled-tags = [
      "diagnostic",
      "experimental",
      "style",
      "performance",
      "opinionated"
    ]

  [linters-settings.gocyclo]
    min-complexity = 15

  [linters-settings.gofumpt]
    extra-rules = true

  [linters-settings.gosimple]
    checks = ["all"]

  [linters-settings.govet]
    check-shadowing = true
    enable-all = true

  [linters-settings.makezero]
    always = true

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.nolintlint]
    allow-no-explanation = ["misspell"]
    require-explanation = true
    require-specific = true

  [linters-settings.prealloc]
    simple = false
    for-loops = true

  [linters-settings.revive]
    ignore-generated-header = true

    [[linters-settings.revive.rules]]
      name = "atomic"

    [[linters-settings.revive.rules]]
      name = "blank-imports"

    [[linters-settings.revive.rules]]
      name = "bool-literal-in-expr"

    [[linters-settings.revive.rules]]
      name = "call-to-gc"

    [[linters-settings.revive.rules]]
      name = "confusing-naming"

    [[linters-settings.revive.rules]]
      name = "confusing-results"

    [[linters-settings.revive.rules]]
      name = "constant-logical-expr"

    [[linters-settings.revive.rules]]
      name = "context-as-argument"

    [[linters-settings.revive.rules]]
      name = "context-keys-type"

    [[linters-settings.revive.rules]]
      name = "defer"

    [[linters-settings.revive.rules]]
      name = "dot-imports"

    [[linters-settings.revive.rules]]
      name = "duplicated-imports"

    [[linters-settings.revive.rules]]
      name = "early-return"

    [[linters-settings.revive.rules]]
      name = "empty-block"

    [[linters-settings.revive.rules]]
      name = "empty-lines"

    [[linters-settings.revive.rules]]
      name = "error-naming"

    [[linters-settings.revive.rules]]
      name = "error-return"

    [[linters-settings.revive.rules]]
      name = "error-strings"

    [[linters-settings.revive.rules]]
      name = "errorf"

    [[linters-settings.revive.rules]]
      name = "exported"

    [[linters-settings.revive.rules]]
      name = "flag-parameter"

    [[linters-settings.revive.rules]]
      name = "get-return"

    [[linters-settings.revive.rules]]
      name = "identical-branches"

    [[linters-settings.revive.rules]]
      name = "if-return"

    [[linters-settings.revive.rules]]
      name = "import-shadowing"

    [[linters-settings.revive.rules]]
      name = "increment-decrement"

    [[linters-settings.revive.rules]]
      name = "indent-error-flow"

    [[linters-settings.revive.rules]]
      name = "modifies-parameter"

    [[linters-settings.revive.rules]]
      name = "modifies-value-receiver"

    [[linters-settings.revive.rules]]
      name = "nested-structs"

    [[linters-settings.revive.rules]]
      name = "optimize-operands-order"

    [[linters-settings.revive.rules]]
      name = "package-comments"

    [[linters-settings.revive.rules]]
      name = "range"

    [[linters-settings.revive.rules]]
      name = "range-val-address"

    [[linters-settings.revive.rules]]
      name = "range-val-in-closure"

    [[linters-settings.revive.rules]]
      name = "receiver-naming"

    [[linters-settings.revive.rules]]
      name = "redefines-builtin-id"

    [[linters-settings.revive.rules]]
      name = "string-of-int"

    [[linters-settings.revive.rules]]
      name = "struct-tag"

    [[linters-settings.revive.rules]]
      name = "superfluous-else"

    [[linters-settings.revive.rules]]
      name = "time-equal"

    [[linters-settings.revive.rules]]
      name = "time-naming"

    [[linters-settings.revive.rules]]
      name = "var-declaration"

    [[linters-settings.revive.rules]]
      name = "var-naming"

    [[linters-settings.revive.rules]]
      name = "unconditional-recursion"

    [[linters-settings.revive.rules]]
      name = "unexported-naming"

    [[linters-settings.revive.rules]]
      name = "unexported-return"

    [[linters-settings.revive.rules]]
      name = "unnecessary-stmt"

    [[linters-settings.revive.rules]]
      name = "unreachable-code"

    [[linters-settings.revive.rules]]
      name = "unused-parameter"

    [[linters-settings.revive.rules]]
      name = "unused-receiver"

    [[linters-settings.revive.rules]]
      name = "use-any"

    [[linters-settings.revive.rules]]
      name = "useless-break"

    [[linters-settings.revive.rules]]
      name = "waitgroup-by-value"

  [linters-settings.sloglint]
    kv-only = true
    args-on-sep-lines = true

  [linters-settings.staticcheck]
    checks = ["all"]

  [linters-settings.stylecheck]
    checks = ["all"]

  [linters-settings.usestdlibvars]
    time-month = true
    time-layout = true
    constant-kind = true

  [linters-settings.unparam]
    check-exported = true

[issues]
max-issues-per-linter = 0
max-same-issues = 0

  [[issues.exclude-rules]]
    path = "_test.go"
    linters = [
      "containedctx",
      "contextcheck",
      "errcheck",
      "gochecknoglobals",
      "goerr113",
      "nilerr",
      "noctx",
      "varnamelen",
      "wrapcheck"
    ]

  [[issues.exclude-rules]]
    path = "_test.go"
    text = "fieldalignment"

  [[issues.exclude-rules]]
    path = "database.go"
    linters = [ "nolintlint" ]
