---
name: 'Lint'
on:
  push:
    branches:
      - 'trunk'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE-3rdparty.csv'
      - 'LICENSE.md'
      - 'NOTICE'
      - 'README.md'
      - 'license-3rdparty.tpl'
  pull_request:
    branches:
      - 'trunk'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE-3rdparty.csv'
      - 'LICENSE.md'
      - 'NOTICE'
      - 'README.md'
      - 'license-3rdparty.tpl'

permissions:
  contents: 'read'

jobs:
  go:
    name: 'Lint Go files'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Setup Go environment'
        uses: 'actions/setup-go@v4'
        with:
          go-version: '1.22.x'

      - name: 'Run govulncheck'
        run: 'make vulnerabilities'

      - name: 'Run gofumpt'
        run: 'make fmt'

      - name: 'Run golangci-lint'
        run: 'make lint'
